spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5431/user
    username: postgres
    password: postgres

  liquibase:
    change-log: db.changelog/db.changelog-master.yml

server:
  port: 8100