version: '3.1'

services:

  order:
    build:
      context: order
      dockerfile: Dockerfile
    image: order:latest
    depends_on:
      - order-db
    ports:
      - "8010:8010"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/order
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  
  product:
    build:
      context: product
      dockerfile: Dockerfile
    image: product:latest
    depends_on:
      - product-db
    ports:
      - "8020:8020"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-db:5432/product
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  order-db:
    image: postgres:14.2
    restart: always
    volumes:
      - ./container-data/order-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  product-db:
    image: postgres:14.2
    restart: always
    volumes:
      - ./container-data/product-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  portainer:
    image: portainer/portainer-ce:2.11.1-alpine
    volumes:
      - ./container-data/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"

  zookeeper:
    image: quay.io/debezium/zookeeper:1.9
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: quay.io/debezium/kafka:1.9
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: quay.io/debezium/connect:1.9
    ports:
      - "8083:8083"
    links:
      - kafka
      - pr
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

