spring:
  application:
    name: orchestrator

  datasource:
    url: jdbc:postgresql://localhost:5435/orchestrator
    username: postgres
    password: postgres

  liquibase:
    change-log: db.changelog/db.changelog-master.yml

server:
  port: 8500