spring:
  application:
    name: billing

  datasource:
    url: jdbc:postgresql://localhost:5432/billing
    username: postgres
    password: postgres

  liquibase:
    change-log: db.changelog/db.changelog-master.yml
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8200